### ISSUE TITLE
Airspy Mini Support

### ISSUE THREAD

**Issue by papasven** [TLeconte/adsbdec#1]
from conversation  https://github.com/TLeconte/vdlm2dec/issues/30
I'dont have good result with "add -D AIRSPY_MINI to the CFLAGS in Makefile" option.

Before I tried it with modified firmware and the result was good

Found AirSpy board 1
Board ID Number: 0 (AIRSPY)
Firmware Version: AirSpy MINI v1.0.0-rc10-3-g7120e77-dirty 2018-04-28
Part ID Number: 0x6906002B 0x00000030
Serial Number: 0x061C67DC286587A3
Supported sample rates:
        10.000000 MSPS
        4.096000 MSPS
        6.000000 MSPS
        3.000000 MSPS
Close board 1

Another attempt with unmodified firmware and 2 changes in air.c also achieved good results.

Found AirSpy board 1
Board ID Number: 0 (AIRSPY)
Firmware Version: AirSpy MINI v1.0.0-rc10-0-g946184a 2016-09-19
Part ID Number: 0x6906002B 0x00000030
Serial Number: 0x061C67DC286587A3
Supported sample rates:
        6.000000 MSPS
        3.000000 MSPS
Close board 1

changes in air.c
		if (supported_samplerates[i] == 10000000)
to
		if (supported_samplerates[i] == 6000000)
and
	result = airspy_set_samplerate(device,  i);
to
	result = airspy_set_samplerate(device,  10000000);

I know it's more a hack and the mini gets very hot without cooling.
The samplerate 10000000 is not official supported by airspy.com for the mini.

best regards

papasven

**Comment by istamov** [comment]
Hi papasven,

I can confirm your results, it does not work with just the CFLAGS modification.

```
pi@raspberrypi:~ $ git clone https://github.com/TLeconte/adsbdec
Cloning into 'adsbdec'...
remote: Enumerating objects: 106, done.
remote: Total 106 (delta 0), reused 0 (delta 0), pack-reused 106
Receiving objects: 100% (106/106), 29.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (61/61), done.
pi@raspberrypi:~ $ cd adsbdec/
pi@raspberrypi:~/adsbdec $ vi Makefile 
pi@raspberrypi:~/adsbdec $ make clean
pi@raspberrypi:~/adsbdec $ make
cc -Wall -Ofast -pthread -I.  `pkg-config --cflags libairspy` -D AIRSPY_MINI   -c -o demod.o demod.c
cc -Wall -Ofast -pthread -I.  `pkg-config --cflags libairspy` -D AIRSPY_MINI   -c -o main.o main.c
cc -Wall -Ofast -pthread -I.  `pkg-config --cflags libairspy` -D AIRSPY_MINI   -c -o crc.o crc.c
cc -Wall -Ofast -pthread -I.  `pkg-config --cflags libairspy` -D AIRSPY_MINI   -c -o output.o output.c
cc -Wall -Ofast -pthread -I.  `pkg-config --cflags libairspy` -D AIRSPY_MINI   -c -o air.o air.c
cc -Wall -Ofast -pthread -I.  `pkg-config --cflags libairspy` -D AIRSPY_MINI   -c -o valid.o valid.c
cc  demod.o main.o crc.o output.o air.o valid.o -lm -pthread  `pkg-config --libs libairspy` -lusb-1.0 -o adsbdec
pi@raspberrypi:~/adsbdec $ ./adsbdec 
did not find needed sampling rate
```

**Comment by TLeconte** [comment]
It's just because I'am an idiot
I commited but I did not push the modifications to github !
Sorry to have make you lost your time.
You could retry now.

**Comment by papasven** [comment]
It works now. 👍
Had made a quick comparison with airspy_adsb.
The decoded messages are not so much, but the number of aircraft is not so different.
1. Image adsbdec
2. Image airspy_adsb

best regards

papasven

![adsbdec](https://user-images.githubusercontent.com/7757396/46757887-c0361f80-cccb-11e8-92f7-a8483c3c0198.png)
![airspy_adsb](https://user-images.githubusercontent.com/7757396/46757911-caf0b480-cccb-11e8-9684-6d3683cfa0a1.png)

**Comment by TLeconte** [comment]
Great !
Thanks

Clearly, I have a conservative approach.
There is two  kind of packets : 
The ones that you could trust because of crc, and the others that you allow, only because, you could thinks they are legitimate. Adsbdec tends too prefer the former than the latter and , I set a detection threshold, that could be too high.

**Comment by TLeconte** [comment]
Just a  question :
Did you run it with -e -d options ?  (error correction and short frames)
Because, without options adsbdec output only DF11/17/18 frames

**Comment by papasven** [comment]
Yes, it was with this options.

`pi@raspberrypi:~/adsbdec# ./adsbdec -d -e -s 192.168.1.15:40005`

**Comment by TLeconte** [comment]
OK one more question . Do you have the last version of airspy_adsb ?
Because previous ones generate lots of duplicates [https://airspy.groups.io/g/main/message/28610](url)
and use the strict mode with airspy_adsb for a  [fair  comparison](https://airspy.groups.io/g/main/message/28611)

PS : nice avatar

**Comment by TLeconte** [comment]
Arrrgh,
Found a big error in crc computation for frame with address/parity (all shrot frames and some long frame).
In fact only DF17/DF18 and some DF11 were decoded successfully.
Got lots of more frame now , particularly with -d option.
If you find some more time for testing ....
Thanks in advance
